[package]
name = "docker-mdbook"
version = "0.1.0"
authors = ["VakeWorks"]
edition = "2025"

[dependencies]
mdbook = "0.4.51"
mdbook-admonish = "1.17.0"
mdbook-mermaid = "0.15.0"
mdbook-toc = "0.14.2"
mdslides = "0.6.1"
mdbook-graphviz = "0.2.1"
