[book]
authors = ["VakeWorks"]
language = "en"
multilingual = false
src = "src"
title = "SovScaDesDisMaLOps Workshop"

[mdslides]
command = "mdslides"
skip_slides = ["how-cheatsheets-work.md", "cpp-cheatsheet.md"]

[preprocessor.graphviz]
command = "mdbook-graphviz"

[output.html.playground]
copyable = true          # include the copy button for copying code snippets
runnable = false

